"""API layer for the Penguin troubleshooting agent."""

import copy
import json
import os
import queue
import subprocess
import threading
from unittest import result
import webview
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4
import re

import ollama
from ollama import chat

from schemas import JSON_SCHEMA
from session_manager import SessionManager
from states import DEFAULT_STATE, STATE_PROMPTS, SYSTEM_PROMPT, InvestigationState

DEFAULT_MODEL = os.getenv("OLLAMA_MODEL", "qwen2.5-coder:3b").strip()

INVESTIGATION_ORDER = [
    "problem",
    "facts",
    "hypothesis",
    "diagnosis",
    "solution",
    "verification",
    "execution"
]

AFFECTED_TO_STATE = {
    "problem": "ProblemStatement",
    "facts": "Facts",
    "hypothesis": "Hypothesis",
    "diagnosis": "Solve",
    "solution": "Solve",
    "verification": "Verification",
    "execution": "TestingHypothesis"
}
class Api:
    def __init__(self,windowobj=None):
        self.state = "ProblemStatement"
        self.user_approved = threading.Event()
        self.problem_statenment=None
        self.windowobj=windowobj
        self.user_msg =[]
        self.hypotheses =[]# list of hypotheses generated by the model
        self.result =[]
        self.hypothesis = [] 
        self.Testcommands = [] # commands to test hypothesis 
        self.facts=[]
        self.command_outputs=[]
        self.verification=[]
        self.evaluation =[]
        self.contradistion_bool = False
        self.solution=[]
        self.chat_history = []
        self.runtime_state = {}
        self.run = None
        self.active_session_id = None
        self._run_session_id = None
        self._investigation_running = False
        self._active_runs = {}
        self._active_runs_lock = threading.Lock()
        self._pending_approvals = {}
        self._shutdown_event = threading.Event()
        self.active_process = None
        self.investigation = InvestigationState()
        self.input_queue = queue.Queue()
        self.continue_event = False
        self.session_manager = SessionManager(Path(__file__).resolve().parent / "sessions.db")
        self.default_model = self.session_manager.load_setting("default_model", DEFAULT_MODEL)
        self.permission_mode = self.session_manager.load_setting("permission_mode", "ask_before_running")
        self.auto_allow = self.permission_mode == "auto_confirm"
        self.current_chat_model = self.default_model
        self.chat_started = False
        self.title = "New Chat"

    @property
    def model(self):
        return self.current_chat_model

    @model.setter
    def model(self, value):
        self.current_chat_model = str(value or "").strip()

    @property
    def investigating_obj(self):
        return self.investigation.obj

    @investigating_obj.setter
    def investigating_obj(self, value):
        if isinstance(value, dict):
            self.investigation.obj = value
        else:
            self.investigation.obj = self.investigation.new_investigation()

    def _reset_runtime_state(self):
        self.state = DEFAULT_STATE
        self.title = "New Chat"
        self.chat_history = []
        self.runtime_state = {}
        self.investigation = InvestigationState()
        self.investigating_obj = self.investigation.new_investigation()
        self.continue_event = False
        self.auto_allow = self.permission_mode == "auto_confirm"
        self.active_session_id = None
        self._run_session_id = None
        self._investigation_running = False
        self._shutdown_event = threading.Event()

    def _clear_pending_approvals(self, shutdown=False):
        if shutdown:
            self._shutdown_event.set()
        else:
            self._shutdown_event.clear()
        self._pending_approvals.clear()

        with self._active_runs_lock:
            for run in list(self._active_runs.values()):
                if shutdown:
                    run._shutdown_event.set()
                else:
                    run._shutdown_event.clear()
                run._pending_approvals.clear()
                run._investigation_running = False

    def _abort_if_stopped(self):
        if self._shutdown_event.is_set():
            self._investigation_running = False
            self._run_session_id = None
            return True
        return False

    def _runtime_snapshot(self):
        return {
            "state": self.state,
            "user_approved": bool(self.user_approved.is_set()),
            "problem_statenment": self.problem_statenment,
            "hypotheses": self.hypotheses,
            "result": self.result,
            "hypothesis": self.hypothesis,
            "Testcommands": self.Testcommands,
            "facts": self.facts,
            "command_outputs": self.command_outputs,
            "verification": self.verification,
            "evaluation": self.evaluation,
            "contradistion_bool": self.contradistion_bool,
            "solution": self.solution,
            "chat_history": self.chat_history,
            "continue_event": self.continue_event,
            "auto_allow": self.auto_allow,
            "chat_started": self.chat_started,
            "current_chat_model": self.current_chat_model,
            "default_model": self.default_model,
            "permission_mode": self.permission_mode,
        }

    def save_current_session(self, title=None):
        snapshot = {
            "id": self.active_session_id,
            "title": title or self.title or "New Chat",
            "created": datetime.now(timezone.utc).isoformat(),
            "modified": datetime.now(timezone.utc).isoformat(),
            "chatHistory": copy.deepcopy(self.chat_history),
            "investigation": copy.deepcopy(self.investigating_obj),
            "isContinue": bool(self.continue_event),
            "auto_allow": bool(self.auto_allow),
            "model": self.current_chat_model or self.default_model,
            "runtime_state": self._runtime_snapshot(),
        }

        if self.active_session_id is None:
            saved = self.session_manager.create_session(snapshot)
            self.active_session_id = saved["id"]
        else:
            snapshot["id"] = self.active_session_id
            saved = self.session_manager.save_session(snapshot)
            self.active_session_id = saved["id"]

        self.runtime_state = copy.deepcopy(saved.get("runtime_state", {}))
        return saved

    def _event_session_id(self):
        if self._investigation_running and self._run_session_id is not None:
            return self._run_session_id
        return self.active_session_id

    def _save_event_to_session(self, session_id, event_obj):
        if session_id is None:
            return

        session = self.session_manager.load_session(str(session_id))
        if session is None:
            return

        history = copy.deepcopy(session.get("chatHistory", []))
        history.append({"role": "system", "content": json.dumps(event_obj, ensure_ascii=False)})
        session["chatHistory"] = history

        runtime_state = copy.deepcopy(session.get("runtime_state", {}))
        runtime_state["chat_history"] = history
        session["runtime_state"] = runtime_state
        self.session_manager.save_session(session)



    def generate_title(self,text, max_words=5):
        # Normalize
        STOP_WORDS = {
        "i", "my", "me", "the", "a", "an", "is", "are", "am",
        "on", "in", "to", "of", "for", "with", "and", "but",
        "how", "why", "what", "can", "does", "do", "please",
        "want", "need", "trying", "get", "getting"
        }
        text = text.strip()
        text = re.sub(r"[^\w\s-]", "", text)

        words = text.split()

        # Remove filler words
        important = [
            word for word in words
            if word.lower() not in STOP_WORDS
        ]

        # Keep first few meaningful words
        title_words = important[:max_words]

        if not title_words:
            return "New Session"

        return " ".join(title_words).capitalize()

    def _remove_command_from_history(self, command):
        session_id = self._event_session_id()
        if session_id is None or not isinstance(command, str):
            return

        session = self.session_manager.load_session(str(session_id))
        if session is None:
            return

        history = copy.deepcopy(session.get("chatHistory", []))
        changed = False
        for entry in history:
            if not isinstance(entry, dict) or not isinstance(entry.get("content"), str):
                continue
            try:
                event = json.loads(entry["content"])
            except json.JSONDecodeError:
                continue

            if event.get("type") != "testing_hypothesis":
                continue
            data = event.get("data")
            tests = data.get("tests") if isinstance(data, dict) else None
            if not isinstance(tests, list):
                continue

            remaining = [
                test for test in tests
                if not (isinstance(test, dict) and test.get("command") == command)
            ]
            if len(remaining) == len(tests):
                continue

            event["data"] = dict(data)
            event["data"]["tests"] = remaining
            entry["content"] = json.dumps(event, ensure_ascii=False)
            changed = True

        if not changed:
            return

        self.chat_history = history
        session["chatHistory"] = history
        runtime_state = copy.deepcopy(session.get("runtime_state", {}))
        runtime_state["chat_history"] = history
        session["runtime_state"] = runtime_state
        self.session_manager.save_session(session)

    def list_sessions(self):
        sessions = self.session_manager.list_sessions()
        return [
            {
                "id": session.get("id"),
                "session_id": session.get("id"),
                "title": session.get("title") or "New Chat",
                "created": session.get("created"),
                "modified": session.get("modified"),
                "updated_at": session.get("modified"),
                "chatHistory": copy.deepcopy(session.get("chatHistory", [])),
                "chat_history": copy.deepcopy(session.get("chatHistory", [])),
                "runtime_state": copy.deepcopy(session.get("runtime_state", {})),
                "auto_allow": bool(session.get("auto_allow", False)),
            }
            for session in sessions
        ]

    def pending_command_ids(self):
        return list(self._pending_approvals.keys())

    def open_session(self, session_id):
        self._clear_pending_approvals(shutdown=False)
        self._investigation_running = False
        self._run_session_id = None
        self._shutdown_event = threading.Event()

        session = self.session_manager.load_session(str(session_id))
        if session is None:
            return {"status": "not_found", "session_id": session_id}

        self.active_session_id = session["id"]
        self.title = session.get("title") or "New Chat"
        self.chat_history = copy.deepcopy(session.get("chatHistory", []))
        self.investigation = InvestigationState()
        self.investigating_obj = copy.deepcopy(session.get("investigation", {}))
        self.continue_event = bool(session.get("isContinue", False))
        self.auto_allow = bool(session.get("auto_allow", False))
        self.current_chat_model = str(session.get("model") or self.default_model).strip()
        self.runtime_state = copy.deepcopy(session.get("runtime_state", {}))

        state_payload = self.runtime_state or {}
        self.state = str(state_payload.get("state") or DEFAULT_STATE)
        self.problem_statenment = state_payload.get("problem_statenment", "")
        self.hypotheses = state_payload.get("hypotheses", [])
        self.result = state_payload.get("result", [])
        self.hypothesis = state_payload.get("hypothesis", [])
        self.Testcommands = state_payload.get("Testcommands", [])
        self.facts = state_payload.get("facts", [])
        self.command_outputs = state_payload.get("command_outputs", [])
        self.verification = state_payload.get("verification", [])
        self.evaluation = state_payload.get("evaluation", [])
        self.contradistion_bool = bool(state_payload.get("contradistion_bool", False))
        self.solution = state_payload.get("solution", [])
        self.chat_started = bool(state_payload.get("chat_started", len(self.chat_history) > 0))

        return {
            "status": "opened",
            "session_id": self.active_session_id,
            "title": session.get("title") or "New Chat",
            "chat_history": copy.deepcopy(self.chat_history),
            "investigation": copy.deepcopy(self.investigating_obj),
            "investigating_obj": copy.deepcopy(self.investigating_obj),
            "runtime_state": copy.deepcopy(self.runtime_state),
            "auto_allow": self.auto_allow,
            "current_chat_model": self.current_chat_model,
            "default_model": self.default_model,
            "chat_started": self.chat_started,
            "pending_command_ids": self.pending_command_ids(),
        }

    def delete_session(self, session_id):
        removed = self.session_manager.delete_session(str(session_id))
        if removed and str(self.active_session_id) == str(session_id):
            self._clear_pending_approvals(shutdown=False)
            self._reset_runtime_state()
        return {
            "status": "deleted" if removed else "not_found",
            "session_id": session_id,
        }

    def create_new_session(self):
        if self.active_session_id is not None:
            self.save_current_session()

        self._clear_pending_approvals(shutdown=False)
        self._reset_runtime_state()
        self.current_chat_model = self.default_model
        self.chat_started = False
        self.auto_allow = self.permission_mode == "auto_confirm"

        created = self.session_manager.create_session(
            {
                "id": None,
                "title": "New Chat",
                "created": datetime.now(timezone.utc).isoformat(),
                "modified": datetime.now(timezone.utc).isoformat(),
                "chatHistory": [],
                "investigation": copy.deepcopy(self.investigating_obj),
                "isContinue": False,
                "auto_allow": self.auto_allow,
                "model": self.current_chat_model,
                "runtime_state": self._runtime_snapshot(),
            }
        )
        self.active_session_id = created["id"]
        self.runtime_state = copy.deepcopy(created.get("runtime_state", {}))

        return {
            "status": "created",
            "session_id": self.active_session_id,
            "id": self.active_session_id,
            "title": created["title"],
            "auto_allow": self.auto_allow,
            "current_chat_model": self.current_chat_model,
            "default_model": self.default_model,
            "chat_started": self.chat_started,
        }

    @staticmethod
    def _is_controller_prompt(message):
        if not isinstance(message, str):
            return False
        cleaned = message.strip()
        return (
            cleaned.startswith("The requested command has finished.")
            and "Choose the next diagnostic step based on the above output." in cleaned
        )

    @staticmethod
    def _is_internal_investigation_payload(message):
        if not isinstance(message, str):
            return False
        cleaned = message.strip()
        if not (cleaned.startswith("{") and cleaned.endswith("}")):
            return False
        try:
            payload = json.loads(cleaned)
        except json.JSONDecodeError:
            return False
        return isinstance(payload, dict) and any(key in payload for key in ["issue", "summary", "facts", "hypotheses", "executed_commands", "next_goal", "confidence"])

    def _sanitize_chat_history(self, history):
        if not isinstance(history, list):
            return []

        cleaned = []
        for entry in history:
            if not isinstance(entry, dict):
                continue
            role = entry.get("role")
            if role == "system":
                continue
            if role == "user":
                content = entry.get("content")
                if self._is_controller_prompt(content):
                    continue
            cleaned.append(copy.deepcopy(entry))
        return cleaned


    def list_models(self):
        installed_models = []
        try:
            models = ollama.list()
            installed_models = [model.model for model in models.models if model.model]
        except Exception:
            installed_models = []

        if self.current_chat_model and self.current_chat_model not in installed_models:
            installed_models.insert(0, self.current_chat_model)

        if not installed_models:
            installed_models = [self.current_chat_model or self.default_model or DEFAULT_MODEL]

        unique_models = []
        for model_name in installed_models:
            if model_name not in unique_models:
                unique_models.append(model_name)

        return unique_models

    def set_model(self, model_name):
        cleaned = str(model_name or "").strip()
        if not cleaned:
            return {"status": "error", "message": "No model selected.", "model": self.current_chat_model}

        if self.chat_started:
            return {"status": "error", "message": "The current chat model is locked.", "model": self.current_chat_model}

        self.current_chat_model = cleaned
        if self.active_session_id is not None:
            self.save_current_session()
        return {"status": "ok", "model": self.current_chat_model}

    def get_settings(self):
        return {
            "default_model": self.default_model,
            "current_chat_model": self.current_chat_model,
            "chat_started": self.chat_started,
            "auto_allow": self.auto_allow,
            "permission_mode": "auto_confirm" if self.auto_allow else "ask_before_running",
        }
    def save_settings(self, payload=None):
        settings = payload or {}
        default_model = str(settings.get("default_model") or "").strip()
        permission_mode = str(settings.get("permission_mode") or "").strip()

        if default_model:
            self.default_model = default_model
            self.session_manager.save_setting("default_model", self.default_model)
            if not self.chat_started:
                self.current_chat_model = self.default_model
                if self.active_session_id is not None:
                    self.save_current_session()

        permission_mode = permission_mode if permission_mode == "auto_confirm" else "ask_before_running"
        self.permission_mode = permission_mode
        self.session_manager.save_setting("permission_mode", permission_mode)
        self.auto_allow = permission_mode == "auto_confirm"
        if self.active_session_id is not None:
            self.save_current_session()

        return {
            "status": "ok",
            "default_model": self.default_model,
            "current_chat_model": self.current_chat_model,
            "chat_started": self.chat_started,
            "permission_mode": "auto_confirm" if self.auto_allow else "ask_before_running",
        }

    def open_settings(self):
        """Navigate the webview to the settings page."""
        try:
            windows = webview.windows
            if windows:
                settings_path = Path(__file__).resolve().parent / "templates" / "settings.html"
                windows[0].load_url(settings_path.as_uri())
            return {"status": "ok"}
        except Exception as e:
            return {"status": "error", "message": str(e)}

    def open_main(self):
        """Navigate the webview back to the main chat page."""
        try:
            windows = webview.windows
            if windows:
                main_path = Path(__file__).resolve().parent / "templates" / "index.html"
                windows[0].load_url(main_path.as_uri())
            return {"status": "ok"}
        except Exception as e:
            return {"status": "error", "message": str(e)}

    def _new_investigation(self):
        return self.investigation.new_investigation()

    def _unique_list(self, items):
        return self.investigation._unique_list(items)

    def _normalize_facts(self, facts):
        return self.investigation._normalize_facts(facts)

    def _merge_hypotheses(self, current, updates):
        return self.investigation.merge_hypotheses(current, updates)

    def _merge_executed_commands(self, current, updates):
        return self.investigation.merge_executed_commands(current, updates)

    def _ensure_next_goal(self):
        return self.investigation.ensure_next_goal(self.state)

    def _reconcile_state(self, parsed=None):
        self.state = self.investigation.reconcile_state(self.state, parsed)

    def _serialize_investigation(self):
        return self.investigation.serialize()

    def run_command_flag(self, command, use_sudo=False):
        """Approve a command that is already waiting in the investigation loop."""
        if not isinstance(command, str) or not command.strip():
            return {"success": False, "output": "", "error": "No command supplied", "return_code": -1}

        if self._shutdown_event.is_set():
            return {"success": False, "output": "", "error": "Command is no longer pending", "return_code": -1}

        approval = self._pending_approvals.get(command)
        if approval is not None:
            approval.set()
            return {"success": True, "output": "", "error": "", "return_code": 0}

        with self._active_runs_lock:
            runs = list(self._active_runs.values())

        for run in reversed(runs):
            if run._shutdown_event.is_set():
                continue
            approval = run._pending_approvals.get(command)
            if approval is not None:
                approval.set()
                return {"success": True, "output": "", "error": "", "return_code": 0}
        return {"success": False, "output": "", "error": "Command is no longer pending", "return_code": -1}

    def stop_agent(self):
        """Stop active generation or approval waits and persist current progress."""
        self._clear_pending_approvals(shutdown=True)
        with self._active_runs_lock:
            active_runs = list(self._active_runs.values())

        for run in active_runs:
            stream = getattr(run, "_active_stream", None)
            close = getattr(stream, "close", None)
            if callable(close):
                try:
                    close()
                except (RuntimeError, ValueError):
                    # A stream can already be unwinding from the generator loop; a
                    # shutdown should remain best-effort instead of crashing the UI.
                    pass
                finally:
                    run._active_stream = None

        if active_runs:
            for run in active_runs:
                run._investigation_running = False
                run.save_current_session()
        else:
            self.save_current_session()
        return {"status": "stopped"}
    def _record_command(self, command, success, output):
        executions = self.investigating_obj.setdefault("executed_commands", [])
        execution = {
            "command": command,
            "success": success,
            "output": output,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "session_id": self._event_session_id(),
        }
        executions.append(execution)

    def _should_run_command(self, command):
        executions = self.investigating_obj.get("executed_commands", [])
        if not executions:
            return True

        # Consider only executions from the current active session when
        # deciding whether a command was just-run. This avoids treating
        # identical commands run in other sessions as if they were run
        # immediately prior in this session.
        if self.active_session_id is None:
            # no active session: fall back to checking the very last entry
            last_entry = executions[-1]
            return not (isinstance(last_entry, dict) and last_entry.get("command") == command)

        # Walk backwards to find the most recent execution for this session
        last_entry_for_session = None
        for entry in reversed(executions):
            if not isinstance(entry, dict):
                continue
            if entry.get("session_id") == self.active_session_id:
                last_entry_for_session = entry
                break

        if last_entry_for_session is None:
            # no previous executions in this session
            return True

        return not (last_entry_for_session.get("command") == command)

    def run_command(self, command, use_sudo=False, command_id=None):
        """Execute a shell command after explicit approval and emit output through the event stream."""
        command_id = command_id or command
        approval = None
        if not self.auto_allow:
            approval = self._pending_approvals.setdefault(command_id, threading.Event())
            try:
                while not approval.wait(timeout=0.5):
                    if self._shutdown_event.is_set():
                        return {
                            "success": False,
                            "output": "",
                            "error": "Command approval cancelled because the investigation stopped.",
                            "return_code": -1,
                        }
            finally:
                self._pending_approvals.pop(command_id, None)

        try:
            if use_sudo:
                command = f"sudo {command}"

            result = subprocess.run(
                command,
                shell=True,
                capture_output=True,
                text=True,
                timeout=120,
            )
            output = result.stdout or result.stderr or ""
            self._record_command(command, result.returncode == 0, output)
            self._remove_command_from_history(command)

            output_payload = {
                "command": command,
                "success": result.returncode == 0,
                "output": result.stdout or "",
                "error": result.stderr or "",
                "return_code": result.returncode,
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "session_id": self._event_session_id(),
            }

            if self.windowobj is not None:
                self.sendEvent([output_payload], "command_outputs")

            return {
                "success": result.returncode == 0,
                "output": output,
                "error": result.stderr,
                "return_code": result.returncode,
            }
        except subprocess.TimeoutExpired:
            self._record_command(command, False, "Command timed out after 30 seconds")
            self._remove_command_from_history(command)
            error = "Command timed out after 30 seconds"
            if self.windowobj is not None:
                self.sendEvent([
                    {
                        "command": command,
                        "success": False,
                        "output": "",
                        "error": error,
                        "return_code": -1,
                        "timestamp": datetime.now(timezone.utc).isoformat(),
                        "session_id": self._event_session_id(),
                    }
                ], "command_outputs")
            return {
                "success": False,
                "output": "",
                "error": error,
                "return_code": -1,
            }
        except Exception as e:
            self._record_command(command, False, str(e))
            self._remove_command_from_history(command)
            error = str(e)
            if self.windowobj is not None:
                self.sendEvent([
                    {
                        "command": command,
                        "success": False,
                        "output": "",
                        "error": error,
                        "return_code": -1,
                        "timestamp": datetime.now(timezone.utc).isoformat(),
                        "session_id": self._event_session_id(),
                    }
                ], "command_outputs")
            return {"success": False, "output": "", "error": error, "return_code": -1}
        finally:
            if approval is not None:
                self._pending_approvals.pop(command_id, None)

    def sendEvent(self,data,Data_type):
        session_id = self._event_session_id()
        event_obj = {
            "data": data,
            "type": Data_type.lower().replace(" ", "_"),
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "session_id": session_id,
        }
        if session_id == self.active_session_id:
            self.runtime_state = self._runtime_snapshot()
            self.chat_history.append({"role": "system", "content": json.dumps(event_obj, ensure_ascii=False)})
            self.save_current_session()
        else:
            self._save_event_to_session(session_id, event_obj)
        if self.windowobj is not None:
            self.windowobj.evaluate_js(f"window.handleInvestigationEvent({json.dumps(event_obj)})")

            
    def contradictionloop(self):
        print(f"[model] CheckHypothesisContradiction: {self.current_chat_model}", flush=True)

        self.contradistion_bool= self.investigation.CheckHypothesisContradiction(
            model_name=self.current_chat_model,
            command_outputs=self.result,
            hypothesis=self.hypothesis
        )
        if self.contradistion_bool is None:
            return
        if self.contradistion_bool["contradicts"]:
            self.state = "HypothesisUpdate"
            self.controller(next_step="HypothesisUpdate")
        else:
            self.state = "Solve"
            self.controller(next_step="Solve")

    def verificationloop(self):
        print(f"[model] Verification command: {self.current_chat_model}", flush=True)
        self.verification = self.investigation.verifiRemediation(
            problem_statement=self.problem_statenment,
            model_name=self.current_chat_model,
            command_outputs=self.command_outputs,
        )
        if self.verification is None:
            return
        step = self.verification.get("step") if isinstance(self.verification, dict) else None

        if isinstance(step, dict):
            step.setdefault("command_id", str(uuid4()))
            if not self.auto_allow:
                self._pending_approvals.setdefault(step["command_id"], threading.Event())

        self.sendEvent(
            data={"step": step, "auto_allow": self.auto_allow},
            Data_type="verification",
        )
        verification_result = self.run_command(step["command"], command_id=step.get("command_id"))

        print(f"[model] Verification evaluator: {self.current_chat_model}", flush=True)

        self.evaluation = self.investigation.verifi(
            problem_statement=self.problem_statenment,
            model_name=self.current_chat_model,
            command_outputs=verification_result,
        )
        if self.evaluation is None:
            return
        if self.evaluation.get("solved") is True:
            self.state = "IssueResolved"
            self.controller(next_step="IssueResolved")
        else:
            self.state = "Solve"
            self.controller(next_step="Solve")

    def issueResolved(self):
        self.sendEvent(
            data={
                "title": "Issue Resolved",
                "message": "The issue has been resolved and verified.",
                "summary": self.solution if isinstance(self.solution, dict) else self.verification,
                "solved": True,
            },
            Data_type="issue_resolved",
        )

    def solver(self):
        print(f"[model] Solve: {self.current_chat_model}", flush=True)
        self.solution = self.investigation.generateSolution(
        problem_statement=self.problem_statenment,
        facts=self.facts,
        model_name=self.current_chat_model,
        relevant_command_outputs=self.command_outputs,hypothesis=self.hypothesis
        )
        if self.solution is None:
            return
        step = self.solution.get("step") if isinstance(self.solution, dict) else None
        if isinstance(step, dict):
            step.setdefault("command_id", str(uuid4()))
            if not self.auto_allow:
                self._pending_approvals.setdefault(step["command_id"], threading.Event())

        self.sendEvent(
                    data={"step": step, "auto_allow": self.auto_allow, **({} if not isinstance(self.solution, dict) else {k: v for k, v in self.solution.items() if k != "step"})},
                    Data_type="solution"
                )
        self.result = self.run_command(step["command"], command_id=step.get("command_id"))

        if self.result["return_code"] == 0:
            self.state = "Verification"
            self.controller(next_step="Verification")
        else:
            self.state = "CheckHypothesisContradiction"
            self.controller(next_step="CheckHypothesisContradiction")
    
    def UpdateHypothesis(self):
        print(f"[model] UpdateHypothesis: {self.current_chat_model}", flush=True)
        self.hypotheses = self.investigation.generateHypothesis(user_request=self.problem_statenment,model_name=self.current_chat_model,facts=self.facts,command_outputs=self.command_outputs)
        if self.hypotheses is None:
            return
        self.sendEvent(
            data=self.hypotheses,
            Data_type="hypotheses"
        )
        
        SOLVER_THRESHOLD = 0.9
        for hypothesis in self.hypotheses["hypotheses"]:
            if hypothesis["confidence"] >= SOLVER_THRESHOLD:
                self.hypothesis = hypothesis
                self.state = "Solve"
                self.controller(next_step="Solve")
            else:
                self.state = "Hypothesis"
                self.controller(next_step="Hypothesis")
        
    def GenerateFacts(self,next_step):
        print(f"[model] Facts: {self.current_chat_model}", flush=True)
        self.facts = self.investigation.generateFacts(
                    problem_statement=self.problem_statenment,
                    facts = self.facts,
                    command_outputs=self.command_outputs,
                    model_name=self.current_chat_model
                )
        if self.facts is None:
            return
        
        self.sendEvent(
                    data=self.facts,
                    Data_type="facts"
                )
        
        self.state = next_step
        self.controller(next_step=next_step)

    def GenerateHypothesis(self,next_step):
        print(f"[model] Hypothesis: {self.current_chat_model}", flush=True)
        self.hypotheses = self.investigation.generateHypothesis(user_request=self.problem_statenment,model_name=self.current_chat_model)
        if self.hypotheses is None:
            return
        
        self.sendEvent(
            data=self.hypotheses,
            Data_type="hypotheses"
        )
        
        self.state = next_step
        self.controller(next_step=next_step)

    def testHypothesis(self,next_step):
        self.command_outputs = []
        
        for hypothesis in self.hypotheses["hypotheses"]:

            self.Testcommands = self.investigation.generateCommandsToTestHypothesis(
                problem_statement=self.problem_statenment,
                hypothesis=hypothesis,
                model_name=self.current_chat_model
            )
            if self.Testcommands is None:
                return
            
            tests = self.Testcommands.get("tests", [])
            for test in tests:
                if isinstance(test, dict):
                    test.setdefault("command_id", str(uuid4()))
                    if not self.auto_allow:
                        self._pending_approvals.setdefault(test["command_id"], threading.Event())
            self.sendEvent(
            data={
                "hypothesis": hypothesis,
                "tests": tests,
                "auto_allow": self.auto_allow,
            },
            Data_type="testing_hypothesis"
            )

            # input("Press Enter to execute the tests...")

            for test in tests:
                result = self.run_command(test["command"], command_id=test.get("command_id"))
                self.command_outputs.append(result)
                self.sendEvent(
                    data=self.command_outputs,
                    Data_type="command_outputs"
                )

            self.sendEvent(
                data={"hypothesis": hypothesis},
                Data_type="hypothesis_tested"
            )
        self.state = next_step
        self.controller(next_step=next_step)

    def StartInvetigation(self,user_input,attached_path,attached,next_step="Hypothesis"):
        # run only once
        # run only once

        if self.title == "New Chat" or not self.title:
            self.title = self.generate_title(user_input)

        # run only once
        if self.run is None:
            self.run = Api(self.windowobj)
            self.run.investigation = self.investigation

        # run every time
        run = self.run

        user_input=''
        for i in self.user_msg:
            user_input = f"{user_input}{i}"

        # run every time
        if self._shutdown_event.is_set():
            return {"status": "stopped"}

        self._shutdown_event.clear()

        # run = Api(self.windowobj)

        run.title = self.title
        run.session_manager = self.session_manager
        run.default_model = self.default_model
        run.permission_mode = self.permission_mode
        run.auto_allow = self.auto_allow
        run.current_chat_model = self.current_chat_model
        run.active_session_id = self.active_session_id
        run.chat_history = self.chat_history
        run.chat_started = True
        self.chat_started = True
        run._active_runs = self._active_runs
        run._active_runs_lock = self._active_runs_lock
        run._pending_approvals = self._pending_approvals
        run._shutdown_event = self._shutdown_event
        
        run.investigation = self.investigation
        run.investigation._stream_owner = run

        with self._active_runs_lock:
            self._active_runs[id(run)] = run

        try:
            result = run._start_investigation(
                user_input,
                attached_path,
                attached,
                next_step
            )

            # Sync state from child Api back to main Api
            self.problem_statenment = run.problem_statenment
            self.state = run.state
            self.hypotheses = run.hypotheses
            self.facts = run.facts
            self.hypothesis = run.hypothesis
            self.command_outputs = run.command_outputs
            self.solution = run.solution
            self.verification = run.verification

            return result
        finally:
            with self._active_runs_lock:
                self._active_runs.pop(id(run), None)

    def _start_investigation(self,user_input,attached_path,attached,next_step="Hypothesis"):
        if self._abort_if_stopped():
            return
        self._run_session_id = self.active_session_id
        self._investigation_running = True
        try:
            self.sendEvent(
            data="user_input",
            Data_type="pre_problem"
            )

            self.runtime_state = self._runtime_snapshot()
            self.save_current_session()
            print(f"[model] ProblemStatement: {self.current_chat_model}", flush=True)
            self.problem_statenment = self.investigation.generateProblemStatement(
                user_request=user_input,
                model_name=self.current_chat_model
            )

            if self.problem_statenment is None:
                return

            
            self.problem_statenment = json.loads(self.problem_statenment)

            self.sendEvent(
                data=self.problem_statenment,
                Data_type="Problem_Statement"
            )
            self.state = next_step
            self.controller(next_step=next_step)
        finally:
            self._investigation_running = False
            self._run_session_id = None
        # Start the diagnosis loop after problem statement is identified
    def generateDecisionOnMsg(self, user_msg):

            

        self.Desicion = self.investigation.decideOnUserMsg(
            user_msg=user_msg,
            hypothesis=self.hypotheses,
            facts=self.facts,
            model_name=self.current_chat_model
        )

        self.sendEvent(
            data=self.Desicion,
            Data_type="Desicion"
        )

        return self.Desicion
        
    def controller(self,user_input=None,attached_path="",attached="",next_step="ProblemStatement",history=None):

        if history == None and user_input != None:
            self.sendEvent(
                        data=user_input,
                        Data_type="user"
                    )

        if isinstance(user_input, str) and user_input.strip():
            self._shutdown_event.clear()

        if self._abort_if_stopped():
            return
    
        if user_input:
            self.user_msg.append(user_input)

        
        if len(self.user_msg) > 1 and user_input is not None and self.problem_statenment != None:
            self.state = "Decision"

        if self.state == "ProblemStatement":
            self.StartInvetigation(user_input,attached_path,attached,next_step="Hypothesis")

        elif self.state == "Hypothesis":
            self.GenerateHypothesis(next_step="TestingHypothesis")

        elif self.state == "TestingHypothesis":
            self.testHypothesis(next_step="Facts")

        
        elif self.state == "Facts":
            self.GenerateFacts(next_step="HypothesisUpdate")

        elif self.state == "HypothesisUpdate":
            self.UpdateHypothesis()

        elif self.state == "Solve":
            self.solver()

        elif self.state == "Verification":
            self.verificationloop()

        elif self.state == "CheckHypothesisContradiction":
            self.contradictionloop()

        elif self.state == "IssueResolved":
            self.issueResolved()
        elif self.state == "Decision":
            decision = self.generateDecisionOnMsg(user_input)

            if decision["action"] == "continue":
                self.controller(next_step=self.state)
                return

            if decision["action"] == "reassess":
                affected = [
                    item for item in decision.get("affected", [])
                    if item in INVESTIGATION_ORDER
                ]

                if not affected:
                    self.controller(next_step=self.state)
                    return

                highest_affected = min(
                    affected,
                    key=lambda x: INVESTIGATION_ORDER.index(x)
                )

                self.state = AFFECTED_TO_STATE[highest_affected]
                self.controller(next_step=self.state)
