"""API layer for the Penguin troubleshooting agent."""

import copy
import json
import os
import queue
import subprocess
import threading
from unittest import result
import webview
from datetime import datetime, timezone
from pathlib import Path

from ollama import chat

from schemas import JSON_SCHEMA
from session_manager import SessionManager
from states import DEFAULT_STATE, STATE_PROMPTS, SYSTEM_PROMPT, InvestigationState

DEFAULT_MODEL = os.getenv("OLLAMA_MODEL", "qwen2.5-coder:3b").strip()


class Api:
    def __init__(self,windowobj=None):
        self.state = "ProblemStatement"
        self.user_approved = threading.Event()
        self.problem_statenment=""
        self.windowobj=windowobj
        self.hypotheses =[]# list of hypotheses generated by the model
        self.result =[]
        self.hypothesis = [] 
        self.Testcommands = [] # commands to test hypothesis 
        self.facts=[]
        self.command_outputs=[]
        self.verification=[]
        self.evaluation =[]
        self.contradistion_bool = False
        self.solution=[]
        self.chat_history = []
        self.active_session_id = None
        self.active_process = None
        self.investigation = InvestigationState()
        self.input_queue = queue.Queue()
        self.continue_event = False
        self.session_manager = SessionManager(Path(__file__).resolve().parent / "sessions.db")
        self.default_model = self.session_manager.load_setting("default_model", DEFAULT_MODEL)
        self.permission_mode = self.session_manager.load_setting("permission_mode", "ask_before_running")
        self.auto_allow = self.permission_mode == "auto_confirm"
        self.current_chat_model = self.default_model
        self.chat_started = False

    @property
    def model(self):
        return self.current_chat_model

    @model.setter
    def model(self, value):
        self.current_chat_model = str(value or "").strip()

    @property
    def investigating_obj(self):
        return self.investigation.obj

    @investigating_obj.setter
    def investigating_obj(self, value):
        if isinstance(value, dict):
            self.investigation.obj = value
        else:
            self.investigation.obj = self.investigation.new_investigation()

    def _reset_runtime_state(self):
        self.state = DEFAULT_STATE
        self.chat_history = []
        self.investigation = InvestigationState()
        self.investigating_obj = self.investigation.new_investigation()
        self.continue_event = False
        self.auto_allow = self.permission_mode == "auto_confirm"
        self.active_session_id = None

    @staticmethod
    def _is_controller_prompt(message):
        if not isinstance(message, str):
            return False
        cleaned = message.strip()
        return (
            cleaned.startswith("The requested command has finished.")
            and "Choose the next diagnostic step based on the above output." in cleaned
        )

    @staticmethod
    def _is_internal_investigation_payload(message):
        if not isinstance(message, str):
            return False
        cleaned = message.strip()
        if not (cleaned.startswith("{") and cleaned.endswith("}")):
            return False
        try:
            payload = json.loads(cleaned)
        except json.JSONDecodeError:
            return False
        return isinstance(payload, dict) and any(key in payload for key in ["issue", "summary", "facts", "hypotheses", "executed_commands", "next_goal", "confidence"])

    def _sanitize_chat_history(self, history):
        if not isinstance(history, list):
            return []

        cleaned = []
        for entry in history:
            if not isinstance(entry, dict):
                continue
            role = entry.get("role")
            if role == "system":
                continue
            if role == "user":
                content = entry.get("content")
                if self._is_controller_prompt(content):
                    continue
            cleaned.append(copy.deepcopy(entry))
        return cleaned

    def _derive_session_title(self):
        for entry in self.chat_history:
            if entry.get("role") == "user" and entry.get("content"):
                content = str(entry["content"]).strip()
                if not content:
                    continue
                try:
                    response = chat(
                        model="smollm2:135m",
                        messages=[
                            {"role": "system", "content": "Generate a concise title for this chat. Reply with ONLY the title, nothing else."},
                            {"role": "user", "content": content},
                        ],
                        stream=False,
                        think=False,
                        options={"num_thread": 2},
                    )
                    title = response.get("message", {}).get("content", "").strip().strip('"').strip("'")
                    words = title.split()
                    if len(words) > 3:
                        title = " ".join(words[:3])
                    return title if title else content[:30]
                except Exception:
                    return content[:30] + ("..." if len(content) > 30 else "")
        return "New Chat"

    def _session_snapshot(self):
        now = datetime.now(timezone.utc).isoformat()
        # When persisting a session, only include executed commands that
        # belong to this session. This prevents commands executed in other
        # sessions from appearing as if they were run in this one.
        investigation_copy = copy.deepcopy(self.investigating_obj) or {}
        executions = investigation_copy.get("executed_commands", [])
        if executions:
            if self.active_session_id is None:
                # Do not persist any executed commands when there is no active
                # session. Commands recorded with session_id=None likely came
                # from previous runs and should not be carried into a new
                # session's saved investigation.
                investigation_copy["executed_commands"] = []
            else:
                filtered = [e for e in executions if not isinstance(e, dict) or e.get("session_id") == self.active_session_id]
                investigation_copy["executed_commands"] = filtered

        return {
            "id": self.active_session_id,
            "title": self._derive_session_title(),
            "created": now,
            "modified": now,
            "chatHistory": self._sanitize_chat_history(self.chat_history),
            "investigation": investigation_copy,
            "isContinue": bool(self.continue_event),
            "auto_allow": bool(self.auto_allow),
            "model": self.current_chat_model,
        }

    def save_current_session(self, title=None):
        snapshot = self._session_snapshot()
        if title:
            snapshot["title"] = title
        if self.active_session_id is None:
            saved = self.session_manager.create_session(snapshot)
            self.active_session_id = saved["id"]
        else:
            snapshot["id"] = self.active_session_id
            saved = self.session_manager.save_session(snapshot)
            self.active_session_id = saved["id"]

        return {
            "session_id": self.active_session_id,
            "id": self.active_session_id,
            "title": saved["title"],
            "updated_at": saved["modified"],
            "auto_allow": self.auto_allow,
            "current_chat_model": self.current_chat_model,
            "default_model": self.default_model,
            "chat_started": self.chat_started,
        }

    def list_sessions(self):
        sessions = self.session_manager.list_sessions()
        return [
            {
                "id": session.get("id"),
                "session_id": session.get("id"),
                "title": session.get("title") or "New Chat",
                "created": session.get("created"),
                "modified": session.get("modified"),
                "updated_at": session.get("modified"),
                "chatHistory": self._sanitize_chat_history(session.get("chatHistory", [])),
                "chat_history": self._sanitize_chat_history(session.get("chatHistory", [])),
                "investigation": copy.deepcopy(session.get("investigation", {})),
                "investigating_obj": copy.deepcopy(session.get("investigation", {})),
                "isContinue": bool(session.get("isContinue", False)),
                "continue_event": bool(session.get("isContinue", False)),
                "auto_allow": bool(session.get("auto_allow", False)),
            }
            for session in sessions
        ]

    def open_session(self, session_id):
        session = self.session_manager.load_session(str(session_id))
        if session is None:
            return {"status": "not_found", "session_id": session_id}

        self.active_session_id = session["id"]
        raw_history = session.get("chatHistory", session.get("chat_history", []))
        self.chat_history = self._sanitize_chat_history(raw_history)
        self.current_chat_model = str(session.get("model") or self.default_model).strip()
        self.investigation = InvestigationState()
        self.investigating_obj = copy.deepcopy(session.get("investigation", {}))
        self.continue_event = bool(session.get("isContinue", False))
        self.auto_allow = bool(session.get("auto_allow", False))
        self.state = DEFAULT_STATE
        self.chat_started = len(self.chat_history) > 0

        return {
            "status": "opened",
            "session_id": self.active_session_id,
            "title": session.get("title") or "New Chat",
            "chat_history": copy.deepcopy(self.chat_history),
            "chatHistory": copy.deepcopy(self.chat_history),
            "investigating_obj": copy.deepcopy(self.investigating_obj),
            "continue_event": self.continue_event,
            "auto_allow": self.auto_allow,
            "current_chat_model": self.current_chat_model,
            "default_model": self.default_model,
            "chat_started": self.chat_started,
        }

    def set_auto_allow(self, enabled):
        self.auto_allow = bool(enabled)
        if self.active_session_id is not None:
            self.save_current_session()
        return {"status": "ok", "auto_allow": self.auto_allow}

    def delete_session(self, session_id):
        removed = self.session_manager.delete_session(str(session_id))
        if removed and self.active_session_id == str(session_id):
            self._reset_runtime_state()
        return {"status": "deleted" if removed else "not_found", "session_id": session_id}

    def create_new_session(self):
        if self.active_session_id is not None:
            self.save_current_session()

        created = self.session_manager.create_session(
            {
                "id": None,
                "title": "New Chat",
                "created": datetime.now(timezone.utc).isoformat(),
                "modified": datetime.now(timezone.utc).isoformat(),
                "chatHistory": [],
                "investigation": {},
                "isContinue": False,
                "auto_allow": self.permission_mode == "auto_confirm",
                "model": self.default_model,
            }
        )
        self._reset_runtime_state()
        self.current_chat_model = self.default_model
        self.chat_started = False
        self.active_session_id = created["id"]
        self.auto_allow = self.permission_mode == "auto_confirm"
        return {
            "status": "created",
            "session_id": self.active_session_id,
            "id": self.active_session_id,
            "title": created["title"],
            "auto_allow": self.auto_allow,
            "current_chat_model": self.current_chat_model,
            "default_model": self.default_model,
            "chat_started": self.chat_started,
        }

    def list_models(self):
        installed_models = []
        try:
            result = subprocess.run(
                ["ollama", "list"],
                capture_output=True,
                text=True,
                check=False,
            )
            if result.returncode == 0:
                for raw_line in result.stdout.splitlines():
                    line = raw_line.strip()
                    if not line or line.startswith("NAME"):
                        continue
                    parts = line.split()
                    if parts:
                        installed_models.append(parts[0])
        except FileNotFoundError:
            installed_models = []

        if self.current_chat_model and self.current_chat_model not in installed_models:
            installed_models.insert(0, self.current_chat_model)

        if not installed_models:
            installed_models = [self.current_chat_model or self.default_model or DEFAULT_MODEL]

        unique_models = []
        for model_name in installed_models:
            if model_name not in unique_models:
                unique_models.append(model_name)

        return unique_models

    def set_model(self, model_name):
        cleaned = str(model_name or "").strip()
        if not cleaned:
            return {"status": "error", "message": "No model selected.", "model": self.current_chat_model}

        if self.chat_started:
            return {"status": "error", "message": "The current chat model is locked.", "model": self.current_chat_model}

        self.current_chat_model = cleaned
        if self.active_session_id is not None:
            self.save_current_session()
        return {"status": "ok", "model": self.current_chat_model}

    def get_settings(self):
        return {
            "default_model": self.default_model,
            "current_chat_model": self.current_chat_model,
            "chat_started": self.chat_started,
            "auto_allow": self.auto_allow,
            "permission_mode": "auto_confirm" if self.auto_allow else "ask_before_running",
        }

    def save_settings(self, payload=None):
        settings = payload or {}
        default_model = str(settings.get("default_model") or "").strip()
        permission_mode = str(settings.get("permission_mode") or "").strip()

        if default_model:
            self.default_model = default_model
            self.session_manager.save_setting("default_model", self.default_model)
            if not self.chat_started:
                self.current_chat_model = self.default_model
                if self.active_session_id is not None:
                    self.save_current_session()

        permission_mode = permission_mode if permission_mode == "auto_confirm" else "ask_before_running"
        self.permission_mode = permission_mode
        self.session_manager.save_setting("permission_mode", permission_mode)
        self.auto_allow = permission_mode == "auto_confirm"
        if self.active_session_id is not None:
            self.save_current_session()

        return {
            "status": "ok",
            "default_model": self.default_model,
            "current_chat_model": self.current_chat_model,
            "chat_started": self.chat_started,
            "permission_mode": "auto_confirm" if self.auto_allow else "ask_before_running",
        }

    def open_settings(self):
        """Navigate the webview to the settings page."""
        try:
            windows = webview.windows
            if windows:
                settings_path = Path(__file__).resolve().parent / "templates" / "settings.html"
                windows[0].load_url(settings_path.as_uri())
            return {"status": "ok"}
        except Exception as e:
            return {"status": "error", "message": str(e)}

    def open_main(self):
        """Navigate the webview back to the main chat page."""
        try:
            windows = webview.windows
            if windows:
                main_path = Path(__file__).resolve().parent / "templates" / "index.html"
                windows[0].load_url(main_path.as_uri())
            return {"status": "ok"}
        except Exception as e:
            return {"status": "error", "message": str(e)}

    def _new_investigation(self):
        return self.investigation.new_investigation()

    def _unique_list(self, items):
        return self.investigation._unique_list(items)

    def _normalize_facts(self, facts):
        return self.investigation._normalize_facts(facts)

    def _merge_hypotheses(self, current, updates):
        return self.investigation.merge_hypotheses(current, updates)

    def _merge_executed_commands(self, current, updates):
        return self.investigation.merge_executed_commands(current, updates)

    def _ensure_next_goal(self):
        return self.investigation.ensure_next_goal(self.state)

    def _reconcile_state(self, parsed=None):
        self.state = self.investigation.reconcile_state(self.state, parsed)

    def _serialize_investigation(self):
        return self.investigation.serialize()

    def build_messages(self, message):
        """Build the messages payload for the model without prior history."""
        investigation_summary = self._serialize_investigation()
        current_state_prompt = STATE_PROMPTS.get(self.state, STATE_PROMPTS[DEFAULT_STATE])
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "system", "content": current_state_prompt},
            {"role": "system", "content": investigation_summary},
            {"role": "system", "content": "Chat History" + str(self.chat_history)},
            {"role": "user", "content": str(message).strip()},
        ]
        return messages

    def _merge_investigation_update(self, update):
        # delegate to InvestigationState and keep local reference in sync
        self.investigation.merge_update(update, self.state)
        self.investigating_obj = self.investigation.obj

    def _transition_state(self, decision):
        # kept for backward compatibility; delegate to InvestigationState
        self.state , self.continue_event = self.investigation.transition_state(decision, self.state)

    def parse_response(self, content):
        if not content:
            return {"reply": "I couldn't generate a response.", "steps": []}

        cleaned = str(content).strip()
        if cleaned.startswith("```"):
            cleaned = cleaned.strip("`").strip()
            if cleaned.startswith("json"):
                cleaned = cleaned[4:].strip()

        try:
            parsed = json.loads(cleaned)
        except json.JSONDecodeError:
            return {"reply": cleaned, "steps": []}

        if isinstance(parsed, dict):
            # honor is_continue provided by the model in the parsed response
            try:
                self.continue_event = bool(parsed.get("is_continue", False))
            except Exception:
                self.continue_event = False
            decision = parsed.get("decision")
            if isinstance(decision, str):
                self._transition_state(decision)
            update = parsed.get("investigation_update")
            if isinstance(update, dict):
                self._merge_investigation_update(update)
            # self._apply_controller_transitions(parsed)
            command = parsed.get("command")
            return {
                "reply": parsed.get("reply", cleaned),
                "decision": self.state,
                "command": command,
                "requires_sudo": parsed.get("requires_sudo", False),
                "steps": parsed.get("steps", []) if isinstance(parsed.get("steps"), list) else [],
                "investigation_update": update,
                "is_continue": self.continue_event,
            }

        return {"reply": cleaned, "steps": []}

    def _compose_user_prompt(self, message, attachment_path=None, attachment_text=None):
        base_message = str(message or "").strip()
        attachment_path = str(attachment_path).strip() if attachment_path else None

        if attachment_text is None and attachment_path:
            attachment_file = Path(attachment_path)
            if attachment_file.exists():
                try:
                    attachment_text = attachment_file.read_text(encoding="utf-8", errors="replace")
                except OSError:
                    attachment_text = ""

        if not attachment_text:
            return base_message

        cleaned_attachment = str(attachment_text).strip()
        if not cleaned_attachment:
            return base_message

        if base_message:
            return (
                f" {base_message} <User message>"
                "Attached log file: "
                f"{attachment_path or 'selected file'}\n\n"
                f"{cleaned_attachment}\n\n"
            )

        return f"Attached log file: {attachment_path or 'selected file'}\n\n{cleaned_attachment}"

    def respond(self, message, attachment_path=None, attachment_text=None):
        """
        Process a user message and generate a response using an Ollama model.
        
        Args:
            message: The user's text message
            attachment_path: Optional path to a file to attach/include
            attachment_text: Optional pre-read attachment content
            
        Returns:
            A dict containing the model's reply, steps, decision, and investigation update
        """
        # Validate input: at least one of message, attachment_path, or attachment_text must be provided
        if not message and not attachment_path and not attachment_text:
            return {"reply": "Please enter a message.", "steps": []}
        
        # If an attachment path is provided, read its contents
        if attachment_path:
            with open(attachment_path,'r') as f:
                attachment_text = f.read()
        
        # Compose the full user prompt by combining message and attachment content
        normalized_message = self._compose_user_prompt(message, attachment_path=attachment_path, attachment_text=attachment_text)
        
        # Return early if the composed message is empty after stripping whitespace
        if not normalized_message.strip():
            return {"reply": "Please enter a message.", "steps": []}

        # Only add to chat history if this is not a controller prompt or internal investigation payload
        # (these are special control messages that shouldn't be stored as regular chat history)
        if not self._is_controller_prompt(normalized_message) and not self._is_internal_investigation_payload(normalized_message):
            # Mark chat as started on first user message
            if not self.chat_started:
                self.chat_started = True
            # Append user message to history and persist the session
            self.chat_history.append({"role": "user", "content": normalized_message})
            self.save_current_session()

        # Build list of candidate models to try, with fallbacks
        candidate_models = []
        if self.current_chat_model:
            candidate_models.append(self.current_chat_model)
        # Add fallback models if not already in the list
        for fallback in ["qwen2.5-coder:3b"]:
            if fallback not in candidate_models:
                candidate_models.append(fallback)
        
        # Track the last error for fallback reporting
        last_error = None
        
        # Try each model in sequence until one succeeds
        for model_name in candidate_models:
            try:
                print(f"[Penguin] Trying Ollama model: {model_name}", flush=True)
                
                # Call the Ollama chat API with the model and built messages
                response = chat(
                    model=model_name,
                    messages=self.build_messages(normalized_message),
                    format=JSON_SCHEMA,
                    stream=False,
                    think=False,
                    keep_alive=-1,
                    options = {
                        "num_thread": 4
                    }
                )
                print(f"[Penguin] Ollama response received from: {model_name}", flush=True)

                # Extract content from response, handling both dict and object response formats
                content = (
                    response.get("message", {}).get("content", "")
                    if isinstance(response, dict)
                    else getattr(getattr(response, "message", None), "content", "")
                )

                # Process the response content if it exists
                if content:
                    # Try to parse content as JSON; if it fails, keep as string
                    assistant_payload = content
                    try:
                        assistant_payload = json.loads(content)
                    except json.JSONDecodeError:
                        assistant_payload = content

                    # Add assistant response to chat history
                    self.chat_history.append({"role": "assistant", "content": assistant_payload})
                    
                    # Update the model that successfully responded
                    self.model = model_name
                    
                    # Parse the response to extract structured data (reply, steps, decision, etc.)
                    parsed = self.parse_response(content)
                    
                    # Persist the updated session with new message
                    self.save_current_session()

                    # Build the response data structure for the frontend
                    response_data = {
                        "reply": parsed.get("reply", ""),
                        "steps": parsed.get("steps", []) if isinstance(parsed.get("steps"), list) else [],
                        "has_more_steps": False,
                        "decision": parsed.get("decision"),
                        "investigation_update": self.investigating_obj,
                        "is_continue": self.continue_event,
                        "auto_allow": self.auto_allow,
                    }

                    # If there are multiple steps, mark as having more steps and include the first one
                    if response_data["steps"]:
                        response_data["has_more_steps"] = len(response_data["steps"]) > 1
                        response_data["next_step"] = response_data["steps"][0]
                    
                    print(response_data)
                    return response_data
                    
            except Exception as exc:
                # Capture error and continue to next model
                last_error = exc
                print(f"[Penguin] Ollama model failed ({model_name}): {exc}", flush=True)

        # If all models failed, return error response
        if last_error is not None:
            return {"reply": "Model Error", "steps": [], "error": str(last_error)}

        # Fallback if no response generated
        return {"reply": "I couldn't generate a response.", "steps": []}

#     def report_command_output(self, command, output, success):
#         """Prepare the next prompt without mutating the visible chat history."""
#         status = "succeeded" if success else "failed"
#         output_text = str(output or "").strip() or "(no output)"

#         next_prompt = f"""
# The requested command has finished.

# Status: {status}

# Command:
# {command}

# Output:
# {output_text}

# Do NOT repeat this command .
# Choose the next diagnostic step based on the above output.
# REMEMBER to change the next goal if the command output indicates that the goal has been achieved or is no longer relevant.
# """
#         return {
#             "status": "reported",
#             "next_prompt": next_prompt,
#             "command_status": status,
#         }
    def run_command_flag(self, command, use_sudo=False):
        """Approve the command and execute it through the real runner."""
        if not isinstance(command, str) or not command.strip():
            return {"success": False, "output": "", "error": "No command supplied", "return_code": -1}

        self.user_approved.clear()
        self.user_approved.set()
        return self.run_command(command, use_sudo=use_sudo)
    def _record_command(self, command, success, output):
        executions = self.investigating_obj.setdefault("executed_commands", [])
        execution = {
            "command": command,
            "success": success,
            "output": output,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "session_id": self.active_session_id,
        }
        executions.append(execution)

    def _should_run_command(self, command):
        executions = self.investigating_obj.get("executed_commands", [])
        if not executions:
            return True

        # Consider only executions from the current active session when
        # deciding whether a command was just-run. This avoids treating
        # identical commands run in other sessions as if they were run
        # immediately prior in this session.
        if self.active_session_id is None:
            # no active session: fall back to checking the very last entry
            last_entry = executions[-1]
            return not (isinstance(last_entry, dict) and last_entry.get("command") == command)

        # Walk backwards to find the most recent execution for this session
        last_entry_for_session = None
        for entry in reversed(executions):
            if not isinstance(entry, dict):
                continue
            if entry.get("session_id") == self.active_session_id:
                last_entry_for_session = entry
                break

        if last_entry_for_session is None:
            # no previous executions in this session
            return True

        return not (last_entry_for_session.get("command") == command)

    def run_command(self, command, use_sudo=False):
        """Execute a shell command after explicit approval and emit output through the event stream."""
        if not self.auto_allow:
            self.user_approved.wait()

        try:
            if use_sudo:
                command = f"sudo {command}"

            result = subprocess.run(
                command,
                shell=True,
                capture_output=True,
                text=True,
                timeout=120,
            )
            output = result.stdout or result.stderr or ""
            self._record_command(command, result.returncode == 0, output)

            output_payload = {
                "command": command,
                "success": result.returncode == 0,
                "output": result.stdout or "",
                "error": result.stderr or "",
                "return_code": result.returncode,
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "session_id": self.active_session_id,
            }

            if self.windowobj is not None:
                self.sendEvent([output_payload], "command_outputs")

            return {
                "success": result.returncode == 0,
                "output": output,
                "error": result.stderr,
                "return_code": result.returncode,
            }
        except subprocess.TimeoutExpired:
            self._record_command(command, False, "Command timed out after 30 seconds")
            error = "Command timed out after 30 seconds"
            if self.windowobj is not None:
                self.sendEvent([
                    {
                        "command": command,
                        "success": False,
                        "output": "",
                        "error": error,
                        "return_code": -1,
                        "timestamp": datetime.now(timezone.utc).isoformat(),
                        "session_id": self.active_session_id,
                    }
                ], "command_outputs")
            return {
                "success": False,
                "output": "",
                "error": error,
                "return_code": -1,
            }
        except Exception as e:
            self._record_command(command, False, str(e))
            error = str(e)
            if self.windowobj is not None:
                self.sendEvent([
                    {
                        "command": command,
                        "success": False,
                        "output": "",
                        "error": error,
                        "return_code": -1,
                        "timestamp": datetime.now(timezone.utc).isoformat(),
                        "session_id": self.active_session_id,
                    }
                ], "command_outputs")
            return {"success": False, "output": "", "error": error, "return_code": -1}
        finally:
            self.user_approved.clear()

    def sendEvent(self,data,Data_type):
        event_obj = {"data": data, "type": Data_type.lower().replace(" ", "_")}
        self.windowobj.evaluate_js(f"window.handleInvestigationEvent({json.dumps(event_obj)})")

            
    def contradictionloop(self):

        self.contradistion_bool= self.investigation.CheckHypothesisContradiction(
            model_name="qwen3:4b",
            command_outputs=self.result,
            hypothesis=self.hypothesis
        )
        if self.contradistion_bool["contradicts"]:
            print("The hypothesis is contradicted by the command output. Re-running the diagnosis loop.")
            self.state = "HypothesisUpdate"
            self.controller(next_step="HypothesisUpdate")
        else:
            self.state = "Solve"
            self.controller(next_step="Solve")


    def verificationloop(self):
        self.verification = self.investigation.verifiRemediation(
        problem_statement=self.problem_statenment,
        # facts=facts,
        model_name="qwen3:4b"
        )
        verification_result = self.run_command(
            self.verification["step"]["command"]
        )
        self.evaluation = self.investigation.verifiRemediation(
            problem_statement=self.problem_statenment,
            command_output=verification_result,
            model_name="qwen3:4b"
        )
        if self.evaluation["solved"]:
            self.state = "IssueResolved"
            self.controller(next_step="IssueResolved")
            pass
        else:   
            self.state = "Solve"
            self.controller(next_step="Solve")
    def issueResolved(self):
        print("The issue has been resolved.")

    def solver(self):
        self.solution = self.investigation.generateSolution(
        problem_statement=self.problem_statenment,
        facts=self.facts,
        model_name="qwen3:4b",
        relevant_command_outputs=self.command_outputs,hypothesis=self.hypothesis
        )
        self.sendEvent(
                    data=self.solution,
                    Data_type="solution"
                )
        print("Solution:")
        print(self.solution)
        self.result = self.run_command(self.solution["step"]["command"])
        print("result")
        print(self.result)

        if self.result["return_code"] == 0:
            self.state = "Verification"
            self.controller(next_step="Verification")
        else:
            self.state = "CheckHypothesisContradiction"
            self.controller(next_step="CheckHypothesisContradiction")
    

    def UpdateHypothesis(self):
        self.hypotheses = self.investigation.generateHypothesis(user_request=self.problem_statenment,model_name="qwen2.5-coder:3b",facts=self.facts,command_outputs=self.command_outputs)
        print("Updated Hypotheses:")
        print(self.hypotheses)
        self.sendEvent(
            data=self.hypotheses,
            Data_type="hypotheses"
        )
        
        SOLVER_THRESHOLD = 0.9
        for hypothesis in self.hypotheses["hypotheses"]:
            if hypothesis["confidence"] >= SOLVER_THRESHOLD:
                self.hypothesis = hypothesis
                self.state = "Solve"
                self.controller(next_step="Solve")
            else:
                self.state = "Hypothesis"
                self.controller(next_step="Hypothesis")
        
    def GenerateFacts(self,next_step):
        self.facts = self.investigation.generateFacts(
                    problem_statement=self.problem_statenment,
                    facts = self.facts,
                    command_outputs=self.command_outputs,
                    model_name="qwen2.5-coder:3b"
                )
        self.sendEvent(
                    data=self.facts,
                    Data_type="facts"
                )
        
        print("Facts:")
        print(self.facts)
        self.state = next_step
        self.controller(next_step=next_step)

    def GenerateHypothesis(self,next_step):
        self.hypotheses = self.investigation.generateHypothesis(user_request=self.problem_statenment,model_name="qwen2.5-coder:3b")
        
        self.sendEvent(
            data=self.hypotheses,
            Data_type="hypotheses"
        )
        
                
        print(self.hypotheses)
        self.state = next_step
        self.controller(next_step=next_step)

    def testHypothesis(self,next_step):
        self.command_outputs = []
        
        for hypothesis in self.hypotheses["hypotheses"]:

            self.Testcommands = self.investigation.generateCommandsToTestHypothesis(
                problem_statement=self.problem_statenment,
                hypothesis=hypothesis,
                model_name="qwen2.5-coder:3b"
            )
            self.sendEvent(
            data={
                "hypothesis": hypothesis,
                "tests": self.Testcommands.get("tests", []),
                "auto_allow": self.auto_allow,
            },
            Data_type="testing_hypothesis"
            )

            print(self.Testcommands)
            # input("Press Enter to execute the tests...")

            for test in self.Testcommands["tests"]:
                result = self.run_command(test["command"])
                print(result)
                self.command_outputs.append(result)
                self.sendEvent(
                    data=self.command_outputs,
                    Data_type="command_outputs"
                )

            self.sendEvent(
                data={"hypothesis": hypothesis},
                Data_type="hypothesis_tested"
            )
        self.state = next_step
        self.controller(next_step=next_step)

    def StartInvetigation(self,user_input,attached_path,attached,next_step="Hypothesis"):

        self.problem_statenment = self.investigation.generateProblemStatement(
            user_request=user_input,
            model_name="qwen2.5-coder:3b"
        )
        print(self.problem_statenment,"\n")
        self.problem_statenment = json.loads(self.problem_statenment)

        self.sendEvent(
            data=self.problem_statenment,
            Data_type="Problem_Statement"
        )
        self.state = next_step
        self.controller(next_step=next_step)
        # Start the diagnosis loop after problem statement is identified
        

    def controller(self,user_input="",attached_path="",attached="",next_step="ProblemStatement"):

        if self.state == "ProblemStatement":
            self.StartInvetigation(user_input,attached_path,attached,next_step="Hypothesis")

        elif self.state == "Hypothesis":
            self.GenerateHypothesis(next_step="TestingHypothesis")

        elif self.state == "TestingHypothesis":
            self.testHypothesis(next_step="Facts")

        elif self.state == "Facts":
            self.GenerateFacts(next_step="HypothesisUpdate")

        elif self.state == "HypothesisUpdate":
            self.UpdateHypothesis()

        elif self.state == "Solve":
            self.solver()

        elif self.state == "Verification":
            self.verificationloop()

        elif self.state == "CheckHypothesisContradiction":
            self.contradictionloop()
            

        